#!/usr/bin/env bash
# Generate web/config.js and web/_redirects for Netlify (proxy mode).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB="$ROOT/web"
API="${PPT_ACADEMIZER_API_URL:-}"
API="${API%/}"

mkdir -p "$WEB"

if [ -n "$API" ]; then
  echo "Netlify: API proxy -> $API"
  cat >"$WEB/config.js" <<EOF
// Generated by scripts/netlify_prepare.sh — same-origin proxy via _redirects
window.__PPT_ACADEMIZER_API__ = "";
EOF
  cat >"$WEB/_redirects" <<EOF
/health  ${API}/health  200
/wizard/preview  ${API}/wizard/preview  200
/analyze  ${API}/analyze  200
/academize  ${API}/academize  200
EOF
else
  echo "Netlify: UI only (set PPT_ACADEMIZER_API_URL to your Python API for conversion)" >&2
  cat >"$WEB/config.js" <<'EOF'
// Set PPT_ACADEMIZER_API_URL at Netlify build, or edit for direct cross-origin API URL.
window.__PPT_ACADEMIZER_API__ = "";
EOF
  cat >"$WEB/_redirects" <<'EOF'
/*    /index.html   200
EOF
fi

echo "Prepared $(wc -l <"$WEB/_redirects" | tr -d ' ') redirect rule(s), config.js"
